### ISSUE TITLE
Purpose of '(' and  ')' parentheses in ListOps

### ISSUE THREAD

**Issue by adamsolomou** [NYU-MLL/spinn#100]
Hi, 

I would like to clarify what is the purpose of the parentheses of type '(' and ')' in the [ListOps dataset](https://github.com/nyu-mll/spinn/tree/listops-release/python/spinn/data/listops). 

In my understanding the order in which the operators are nested is already encapsulated by the brackets of type '[' and ']', so why are the parentheses '(' and ')' needed? Am I missing something? 

Thanks!

**Comment by sleepinyourhat** [comment]
If you're using a typical model like an RNN or Transformer, you should drop the round parens. The round parens are meant to define an exact binary tree for use in binary TreeRNN-style models, like we use in the paper. They can be deterministically derived from the square brackets (using a tiebreaking rule to binarize), but we encode it explicitly to minimize the risk that that goes wrong and provide compatibility with code that handles natural language sentence parses.

**Comment by adamsolomou** [comment]
Thanks for clarifying! I am using a Transformer-based model, so in that case I also agree that the round parens should not play any role. I am closing the issue.
