### ISSUE TITLE
code for ST-gumbel on ListOps dataset

### ISSUE THREAD

**Issue by chijames** [NYU-MLL/spinn#101]
Hi,

Can you point me to the baseline code used for ST-gumbel on ListOps dataset? Thanks!

**Comment by sleepinyourhat** [comment]
Everything we have should be on the branch page here: 

https://github.com/NYU-MLL/spinn/tree/listops-release

We can try to answer questions (+ @woollysocks), though it's been long enough that we'll likely just be sifting through code to answer, so we can't promise to be too useful.
