### ISSUE TITLE
Please put MT architecture behind a flag.

### ISSUE THREAD

**Issue by woollysocks** [NYU-MLL/spinn#93]
Currently, I can't run classification experiments on master. I get the following error since a target_vocabulary is only defined if you're doing MT. 

> Traceback (most recent call last):
>   File "/Users/nikita.nangia/anaconda/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/nikita.nangia/anaconda/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/nikita.nangia/Documents/General/NYU/ML2/research/spinn/python/spinn/models/rl_classifier.py", line 442, in <module>
>     run(only_forward=FLAGS.expanded_eval_only_mode)
>   File "/Users/nikita.nangia/Documents/General/NYU/ML2/research/spinn/python/spinn/models/rl_classifier.py", line 382, in run
>     FLAGS.training_data_path, FLAGS.eval_data_path)
>   File "/Users/nikita.nangia/Documents/General/NYU/ML2/research/spinn/python/spinn/models/base.py", line 196, in load_data_and_embeddings
>     target_vocabulary=target_vocabulary) if raw_training_data is not None else None
> UnboundLocalError: local variable 'target_vocabulary' referenced before assignment

**Comment by woollysocks** [comment]
@anhad13

**Comment by sleepinyourhat** [comment]
If this isn’t being dealt with now. I think it’s reasonable to roll back
all MT related changes for now. AM can fix it on a branch and merge back
later.

**Comment by anhad13** [comment]
I think @woollysocks fixed this. I'll run some NLI experiments just to be sure.

**Comment by sleepinyourhat** [comment]
Cool! Just chiming in from my phone, so not seeing everything.

**Comment by woollysocks** [comment]
Yup! Resolved. Experiments running now.
