### ISSUE TITLE
Run model on arbitrary sentence

### ISSUE THREAD

**Issue by descartesholland** [NYU-MLL/spinn#98]
Sorry for the seemingly amateur question here. The code runs (with some minor modifications initially) to produce models, but I don't see where classifications are outputted/logged, if anywhere. How do I obtain classifications for cases in the test set, for example?

**Comment by descartesholland** [comment]
Is this as simple as examining the "pred" tensor output? 0 : entails, 1 : neutral, 2 : contradiction ?

**Comment by sleepinyourhat** [comment]
Hrm—I haven't touched this code myself in a while (others might chime in), but building a custom test set file and looking at preds should work. Also look into the write_eval_report flag, defined here: https://github.com/nyu-mll/spinn/blob/master/python/spinn/models/base.py#L586
